// Logical dependency graph for the factory electrical distribution
// Power flow: Grid -> Main Transformer -> Main Switchgear -> sub-transformers/boards -> cabinets

export const BUILDINGS = [
  {
    id: 'utility',
    name: 'Utility Building',
    code: 'UTL-01',
    bounds: { x: 40, y: 80, w: 360, h: 540 },
    accent: '#3b82f6',
  },
  {
    id: 'furnace',
    name: 'Furnace Area',
    code: 'FRN-02',
    bounds: { x: 440, y: 80, w: 500, h: 540 },
    accent: '#f97316',
  },
  {
    id: 'batch',
    name: 'Batch House',
    code: 'BTH-03',
    // Visually detached block on the right to communicate "separate building"
    bounds: { x: 990, y: 140, w: 320, h: 420 },
    accent: '#a855f7',
  },
];

// Nodes use absolute coordinates relative to the canvas (1360 x 720 viewport)
export const INITIAL_NODES = [
  // ===== UTILITY BUILDING =====
  {
    id: 'T-MAIN',
    name: 'Main Transformer 15kV/0.4kV',
    type: 'transformer',
    building: 'utility',
    floor: 'Ground',
    coordinates: { x: 120, y: 180 },
    status: 'operational',
    dependsOn: [],
    rating: '2500 kVA',
    voltage: '15kV / 400V',
    installed: '2018-04-12',
  },
  {
    id: 'SG-MAIN',
    name: 'Main LV Switchgear',
    type: 'switchgear',
    building: 'utility',
    floor: 'Ground',
    coordinates: { x: 260, y: 180 },
    status: 'operational',
    dependsOn: ['T-MAIN'],
    rating: '4000A',
    voltage: '400V',
    installed: '2018-05-03',
  },
  {
    id: 'UDB-1',
    name: 'Utility Distribution Board A',
    type: 'distribution',
    building: 'utility',
    floor: 'Ground',
    coordinates: { x: 120, y: 340 },
    status: 'operational',
    dependsOn: ['SG-MAIN'],
    rating: '630A',
    voltage: '400V',
  },
  {
    id: 'UDB-2',
    name: 'Utility Distribution Board B',
    type: 'distribution',
    building: 'utility',
    floor: 'Ground',
    coordinates: { x: 260, y: 340 },
    status: 'operational',
    dependsOn: ['SG-MAIN'],
    rating: '400A',
    voltage: '400V',
  },
  {
    id: 'UC-PUMPS',
    name: 'Cooling Pumps Cabinet',
    type: 'cabinet',
    building: 'utility',
    floor: 'Ground',
    coordinates: { x: 90, y: 490 },
    status: 'operational',
    dependsOn: ['UDB-1'],
    rating: '160A',
  },
  {
    id: 'UC-COMP',
    name: 'Compressor Cabinet',
    type: 'cabinet',
    building: 'utility',
    floor: 'Ground',
    coordinates: { x: 220, y: 490 },
    status: 'operational',
    dependsOn: ['UDB-1'],
    rating: '125A',
  },
  {
    id: 'UC-HVAC',
    name: 'HVAC Control Cabinet',
    type: 'cabinet',
    building: 'utility',
    floor: 'Mezzanine',
    coordinates: { x: 330, y: 490 },
    status: 'operational',
    dependsOn: ['UDB-2'],
    rating: '80A',
  },

  // ===== FURNACE AREA =====
  {
    id: 'T-FURN',
    name: 'Furnace Transformer',
    type: 'transformer',
    building: 'furnace',
    floor: 'Ground',
    coordinates: { x: 500, y: 180 },
    status: 'operational',
    dependsOn: ['SG-MAIN'],
    rating: '1600 kVA',
    voltage: '400V / 690V',
  },
  {
    id: 'FSG',
    name: 'Furnace Main Switchgear',
    type: 'switchgear',
    building: 'furnace',
    floor: 'Ground',
    coordinates: { x: 660, y: 180 },
    status: 'operational',
    dependsOn: ['T-FURN'],
    rating: '2500A',
  },
  {
    id: 'FDB-1',
    name: 'Furnace DB - Zone A',
    type: 'distribution',
    building: 'furnace',
    floor: 'Ground',
    coordinates: { x: 540, y: 340 },
    status: 'operational',
    dependsOn: ['FSG'],
    rating: '800A',
  },
  {
    id: 'FDB-2',
    name: 'Furnace DB - Zone B',
    type: 'distribution',
    building: 'furnace',
    floor: 'Ground',
    coordinates: { x: 780, y: 340 },
    status: 'operational',
    dependsOn: ['FSG'],
    rating: '800A',
  },
  {
    id: 'FC-HEAT-1',
    name: 'Heating Element Cabinet 1',
    type: 'cabinet',
    building: 'furnace',
    floor: 'Ground',
    coordinates: { x: 490, y: 490 },
    status: 'operational',
    dependsOn: ['FDB-1'],
    rating: '400A',
  },
  {
    id: 'FC-HEAT-2',
    name: 'Heating Element Cabinet 2',
    type: 'cabinet',
    building: 'furnace',
    floor: 'Ground',
    coordinates: { x: 600, y: 490 },
    status: 'operational',
    dependsOn: ['FDB-1'],
    rating: '400A',
  },
  {
    id: 'FC-CONV',
    name: 'Conveyor Drive Cabinet',
    type: 'cabinet',
    building: 'furnace',
    floor: 'Ground',
    coordinates: { x: 730, y: 490 },
    status: 'operational',
    dependsOn: ['FDB-2'],
    rating: '250A',
  },
  {
    id: 'FC-EXH',
    name: 'Exhaust Fan Cabinet',
    type: 'cabinet',
    building: 'furnace',
    floor: 'Roof',
    coordinates: { x: 840, y: 490 },
    status: 'operational',
    dependsOn: ['FDB-2'],
    rating: '160A',
  },

  // ===== BATCH HOUSE (separate block) =====
  {
    id: 'T-BATCH',
    name: 'Batch House Transformer',
    type: 'transformer',
    building: 'batch',
    floor: 'Ground',
    coordinates: { x: 1050, y: 220 },
    status: 'operational',
    dependsOn: ['SG-MAIN'],
    rating: '800 kVA',
  },
  {
    id: 'BHSG',
    name: 'Batch House Switchgear',
    type: 'switchgear',
    building: 'batch',
    floor: 'Ground',
    coordinates: { x: 1220, y: 220 },
    status: 'operational',
    dependsOn: ['T-BATCH'],
    rating: '1600A',
  },
  {
    id: 'BHDB',
    name: 'Batch House Distribution Board',
    type: 'distribution',
    building: 'batch',
    floor: 'Ground',
    coordinates: { x: 1140, y: 370 },
    status: 'operational',
    dependsOn: ['BHSG'],
    rating: '400A',
  },
  {
    id: 'BHC-MIX',
    name: 'Mixer Drives Cabinet',
    type: 'cabinet',
    building: 'batch',
    floor: 'Ground',
    coordinates: { x: 1050, y: 500 },
    status: 'operational',
    dependsOn: ['BHDB'],
    rating: '200A',
  },
  {
    id: 'BHC-SILO',
    name: 'Silo Feeders Cabinet',
    type: 'cabinet',
    building: 'batch',
    floor: 'Ground',
    coordinates: { x: 1230, y: 500 },
    status: 'operational',
    dependsOn: ['BHDB'],
    rating: '160A',
  },
];
